# Generated by Django 2.1.5 on 2019-02-04 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180904_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prosopagnosia',
        ),
        migrations.AlterField(
            model_name='subject',
            name='token',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
